// -------------------------------------------------------------
// 
// File Name: hdlsrc\tb_FFT\Complex4Multiply_block1.v
// Created: 2023-02-08 00:35:50
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Complex4Multiply_block1
// Source Path: tb_FFT/DUT/FFT/RADIX22FFT_SDF1_7/Complex4Multiply
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Complex4Multiply_block1
          (clk,
           reset,
           enb,
           din_re,
           din_im,
           din_7_vld_dly,
           twdl_7_1_re,
           twdl_7_1_im,
           dinXTwdl_re,
           dinXTwdl_im,
           dinXTwdl_7_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [22:0] din_re;  // sfix23_En13
  input   signed [22:0] din_im;  // sfix23_En13
  input   din_7_vld_dly;
  input   signed [15:0] twdl_7_1_re;  // sfix16_En14
  input   signed [15:0] twdl_7_1_im;  // sfix16_En14
  output  signed [22:0] dinXTwdl_re;  // sfix23_En13
  output  signed [22:0] dinXTwdl_im;  // sfix23_En13
  output  dinXTwdl_7_1_vld;


  reg signed [22:0] din_re_reg;  // sfix23_En13
  reg signed [22:0] din_im_reg;  // sfix23_En13
  reg signed [15:0] twdl_re_reg;  // sfix16_En14
  reg signed [15:0] twdl_im_reg;  // sfix16_En14
  reg signed [22:0] Complex4Multiply_din1_re_pipe1;  // sfix23
  reg signed [22:0] Complex4Multiply_din1_im_pipe1;  // sfix23
  reg signed [38:0] Complex4Multiply_mult1_re_pipe1;  // sfix39
  reg signed [38:0] Complex4Multiply_mult2_re_pipe1;  // sfix39
  reg signed [38:0] Complex4Multiply_mult1_im_pipe1;  // sfix39
  reg signed [38:0] Complex4Multiply_mult2_im_pipe1;  // sfix39
  reg signed [15:0] Complex4Multiply_twiddle_re_pipe1;  // sfix16
  reg signed [15:0] Complex4Multiply_twiddle_im_pipe1;  // sfix16
  reg signed [38:0] prod1_re;  // sfix39_En27
  reg signed [38:0] prod1_im;  // sfix39_En27
  reg signed [38:0] prod2_re;  // sfix39_En27
  reg signed [38:0] prod2_im;  // sfix39_En27
  reg  din_vld_dly1;
  reg  din_vld_dly2;
  reg  din_vld_dly3;
  reg  prod_vld;
  reg signed [39:0] Complex4Add_multRes_re_reg;  // sfix40
  reg signed [39:0] Complex4Add_multRes_im_reg;  // sfix40
  reg  Complex4Add_prod_vld_reg1;
  reg signed [38:0] Complex4Add_prod1_re_reg;  // sfix39
  reg signed [38:0] Complex4Add_prod1_im_reg;  // sfix39
  reg signed [38:0] Complex4Add_prod2_re_reg;  // sfix39
  reg signed [38:0] Complex4Add_prod2_im_reg;  // sfix39
  wire signed [39:0] Complex4Add_multRes_re_reg_next;  // sfix40_En27
  wire signed [39:0] Complex4Add_multRes_im_reg_next;  // sfix40_En27
  wire signed [39:0] Complex4Add_sub_cast;  // sfix40_En27
  wire signed [39:0] Complex4Add_sub_cast_1;  // sfix40_En27
  wire signed [39:0] Complex4Add_add_cast;  // sfix40_En27
  wire signed [39:0] Complex4Add_add_cast_1;  // sfix40_En27
  wire signed [39:0] mulResFP_re;  // sfix40_En27
  wire signed [39:0] mulResFP_im;  // sfix40_En27
  reg  dinXTwdl_7_1_vld_1;

  initial begin
    Complex4Multiply_din1_re_pipe1 = 23'sb00000000000000000000000;
    Complex4Multiply_din1_im_pipe1 = 23'sb00000000000000000000000;
    Complex4Multiply_twiddle_re_pipe1 = 16'sb0000000000000000;
    Complex4Multiply_twiddle_im_pipe1 = 16'sb0000000000000000;
    Complex4Multiply_mult1_re_pipe1 = 39'sh0000000000;
    Complex4Multiply_mult2_re_pipe1 = 39'sh0000000000;
    Complex4Multiply_mult1_im_pipe1 = 39'sh0000000000;
    Complex4Multiply_mult2_im_pipe1 = 39'sh0000000000;
    prod1_re = 39'sh0000000000;
    prod2_re = 39'sh0000000000;
    prod1_im = 39'sh0000000000;
    prod2_im = 39'sh0000000000;
  end

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_reg <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          din_re_reg <= din_re;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        din_im_reg <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          din_im_reg <= din_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        twdl_re_reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          twdl_re_reg <= twdl_7_1_re;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        twdl_im_reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          twdl_im_reg <= twdl_7_1_im;
        end
      end
    end



  // Complex4Multiply
  always @(posedge clk)
    begin : Complex4Multiply_process
      if (enb) begin
        prod1_re <= Complex4Multiply_mult1_re_pipe1;
        prod2_re <= Complex4Multiply_mult2_re_pipe1;
        prod1_im <= Complex4Multiply_mult1_im_pipe1;
        prod2_im <= Complex4Multiply_mult2_im_pipe1;
        Complex4Multiply_mult1_re_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_re_pipe1;
        Complex4Multiply_mult2_re_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_im_pipe1;
        Complex4Multiply_mult1_im_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_im_pipe1;
        Complex4Multiply_mult2_im_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_re_pipe1;
        Complex4Multiply_twiddle_re_pipe1 <= twdl_re_reg;
        Complex4Multiply_twiddle_im_pipe1 <= twdl_im_reg;
        Complex4Multiply_din1_re_pipe1 <= din_re_reg;
        Complex4Multiply_din1_im_pipe1 <= din_im_reg;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        din_vld_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          din_vld_dly1 <= din_7_vld_dly;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        din_vld_dly2 <= 1'b0;
      end
      else begin
        if (enb) begin
          din_vld_dly2 <= din_vld_dly1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        din_vld_dly3 <= 1'b0;
      end
      else begin
        if (enb) begin
          din_vld_dly3 <= din_vld_dly2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        prod_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          prod_vld <= din_vld_dly3;
        end
      end
    end



  // Complex4Add
  always @(posedge clk or posedge reset)
    begin : Complex4Add_process
      if (reset == 1'b1) begin
        Complex4Add_multRes_re_reg <= 40'sh0000000000;
        Complex4Add_multRes_im_reg <= 40'sh0000000000;
        Complex4Add_prod1_re_reg <= 39'sh0000000000;
        Complex4Add_prod1_im_reg <= 39'sh0000000000;
        Complex4Add_prod2_re_reg <= 39'sh0000000000;
        Complex4Add_prod2_im_reg <= 39'sh0000000000;
        Complex4Add_prod_vld_reg1 <= 1'b0;
        dinXTwdl_7_1_vld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Complex4Add_multRes_re_reg <= Complex4Add_multRes_re_reg_next;
          Complex4Add_multRes_im_reg <= Complex4Add_multRes_im_reg_next;
          Complex4Add_prod1_re_reg <= prod1_re;
          Complex4Add_prod1_im_reg <= prod1_im;
          Complex4Add_prod2_re_reg <= prod2_re;
          Complex4Add_prod2_im_reg <= prod2_im;
          dinXTwdl_7_1_vld_1 <= Complex4Add_prod_vld_reg1;
          Complex4Add_prod_vld_reg1 <= prod_vld;
        end
      end
    end

  assign Complex4Add_sub_cast = {Complex4Add_prod1_re_reg[38], Complex4Add_prod1_re_reg};
  assign Complex4Add_sub_cast_1 = {Complex4Add_prod2_re_reg[38], Complex4Add_prod2_re_reg};
  assign Complex4Add_multRes_re_reg_next = Complex4Add_sub_cast - Complex4Add_sub_cast_1;
  assign Complex4Add_add_cast = {Complex4Add_prod1_im_reg[38], Complex4Add_prod1_im_reg};
  assign Complex4Add_add_cast_1 = {Complex4Add_prod2_im_reg[38], Complex4Add_prod2_im_reg};
  assign Complex4Add_multRes_im_reg_next = Complex4Add_add_cast + Complex4Add_add_cast_1;
  assign mulResFP_re = Complex4Add_multRes_re_reg;
  assign mulResFP_im = Complex4Add_multRes_im_reg;



  assign dinXTwdl_re = mulResFP_re[36:14];



  assign dinXTwdl_im = mulResFP_im[36:14];



  assign dinXTwdl_7_1_vld = dinXTwdl_7_1_vld_1;

endmodule  // Complex4Multiply_block1

