// -------------------------------------------------------------
// 
// File Name: hdlsrc\tb_FFT\RADIX22FFT_SDF1_1.v
// Created: 2023-02-08 00:35:49
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_1
// Source Path: tb_FFT/DUT/FFT/RADIX22FFT_SDF1_1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_1
          (clk,
           reset,
           enb,
           din_1_1_re_dly,
           din_1_1_im_dly,
           din_1_vld_dly,
           rd_1_Addr,
           rd_1_Enb,
           proc_1_enb,
           dout_1_1_re,
           dout_1_1_im,
           dout_1_1_vld,
           dinXTwdl_1_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] din_1_1_re_dly;  // sfix16_En13
  input   signed [15:0] din_1_1_im_dly;  // sfix16_En13
  input   din_1_vld_dly;
  input   [8:0] rd_1_Addr;  // ufix9
  input   rd_1_Enb;
  input   proc_1_enb;
  output  signed [16:0] dout_1_1_re;  // sfix17_En13
  output  signed [16:0] dout_1_1_im;  // sfix17_En13
  output  dout_1_1_vld;
  output  dinXTwdl_1_1_vld;


  wire signed [16:0] din_re;  // sfix17_En13
  reg signed [16:0] dinXTwdl_re;  // sfix17_En13
  wire signed [16:0] din_im;  // sfix17_En13
  reg signed [16:0] dinXTwdl_im;  // sfix17_En13
  reg  dinXTwdl_1_1_vld_1;
  wire signed [16:0] x_im;  // sfix17_En13
  reg  x_vld;
  wire signed [16:0] wrData_re;  // sfix17_En13
  wire [8:0] wrAddr;  // ufix9
  wire wrEnb;
  wire signed [16:0] x_re;  // sfix17_En13
  reg signed [17:0] Radix22ButterflyG1_btf1_re_reg;  // sfix18
  reg signed [17:0] Radix22ButterflyG1_btf1_im_reg;  // sfix18
  reg signed [17:0] Radix22ButterflyG1_btf2_re_reg;  // sfix18
  reg signed [17:0] Radix22ButterflyG1_btf2_im_reg;  // sfix18
  reg signed [16:0] Radix22ButterflyG1_x_re_dly1;  // sfix17
  reg signed [16:0] Radix22ButterflyG1_x_im_dly1;  // sfix17
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [16:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix17
  reg signed [16:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix17
  reg signed [16:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix17
  reg signed [16:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix17
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [17:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_add_cast;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_add_cast_1;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_sub_cast;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_sub_cast_1;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_add_cast_2;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_add_cast_3;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_sub_cast_2;  // sfix18_En13
  wire signed [17:0] Radix22ButterflyG1_sub_cast_3;  // sfix18_En13
  reg signed [16:0] xf_re;  // sfix17_En13
  reg signed [16:0] xf_im;  // sfix17_En13
  reg  xf_vld;
  wire signed [16:0] dinXTwdlf_re;  // sfix17_En13
  wire signed [16:0] dinXTwdlf_im;  // sfix17_En13
  wire dinxTwdlf_vld;
  wire signed [16:0] btf1_re;  // sfix17_En13
  wire signed [16:0] btf1_im;  // sfix17_En13
  wire signed [16:0] btf2_re;  // sfix17_En13
  wire signed [16:0] btf2_im;  // sfix17_En13
  reg  btf_vld;


  assign din_re = {din_1_1_re_dly[15], din_1_1_re_dly};



  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinXTwdl_re <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          dinXTwdl_re <= din_re;
        end
      end
    end



  assign din_im = {din_1_1_im_dly[15], din_1_1_im_dly};



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinXTwdl_im <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          dinXTwdl_im <= din_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinXTwdl_1_1_vld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          dinXTwdl_1_1_vld_1 <= din_1_vld_dly;
        end
      end
    end



  assign x_im = 17'sb00000000000000000;



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_1_Enb;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(9),
                              .DataWidth(17)
                              )
                            u_dataMEM_re_0_1_generic (.clk(clk),
                                                      .enb(enb),
                                                      .wr_din(wrData_re),
                                                      .wr_addr(wrAddr),
                                                      .wr_en(wrEnb),
                                                      .rd_addr(rd_1_Addr),
                                                      .rd_dout(x_re)
                                                      );

  // Radix22ButterflyG1
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 18'sb000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 18'sb000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 18'sb000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 18'sb000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 17'sb00000000000000000;
        xf_im <= 17'sb00000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 17'sb00000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 17'sb00000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_1_enb && dinXTwdl_1_1_vld_1;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_1_enb) && dinXTwdl_1_1_vld_1;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[16], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[16], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[16], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[16], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[16], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[16], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[16], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[16], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[16:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[16:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[16:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[16:0];



  SDFCommutator1 u_SDFCOMMUTATOR_1 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_1_vld_dly(din_1_vld_dly),
                                    .xf_re(xf_re),  // sfix17_En13
                                    .xf_im(xf_im),  // sfix17_En13
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix17_En13
                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix17_En13
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  // sfix17_En13
                                    .btf1_im(btf1_im),  // sfix17_En13
                                    .btf2_re(btf2_re),  // sfix17_En13
                                    .btf2_im(btf2_im),  // sfix17_En13
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  // sfix17_En13
                                    .wrAddr(wrAddr),  // ufix9
                                    .wrEnb(wrEnb),
                                    .dout_1_1_re(dout_1_1_re),  // sfix17_En13
                                    .dout_1_1_im(dout_1_1_im),  // sfix17_En13
                                    .dout_1_1_vld(dout_1_1_vld)
                                    );

  assign dinXTwdl_1_1_vld = dinXTwdl_1_1_vld_1;

endmodule  // RADIX22FFT_SDF1_1

