// -------------------------------------------------------------
// 
// File Name: hdlsrc\tb_FFT\RADIX22FFT_SDF2_8.v
// Created: 2023-02-08 00:35:50
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF2_8
// Source Path: tb_FFT/DUT/FFT/RADIX22FFT_SDF2_8
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF2_8
          (clk,
           reset,
           enb,
           dout_7_1_re,
           dout_7_1_im,
           dout_7_1_vld,
           rd_8_Addr,
           rd_8_Enb,
           proc_8_enb,
           multiply_8_J,
           dout_8_1_re,
           dout_8_1_im,
           dout_8_1_vld,
           dinXTwdl_8_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [22:0] dout_7_1_re;  // sfix23_En13
  input   signed [22:0] dout_7_1_im;  // sfix23_En13
  input   dout_7_1_vld;
  input   [1:0] rd_8_Addr;  // ufix2
  input   rd_8_Enb;
  input   proc_8_enb;
  input   multiply_8_J;
  output  signed [23:0] dout_8_1_re;  // sfix24_En13
  output  signed [23:0] dout_8_1_im;  // sfix24_En13
  output  dout_8_1_vld;
  output  dinXTwdl_8_1_vld;


  wire signed [23:0] din_re;  // sfix24_En13
  wire signed [23:0] din_im;  // sfix24_En13
  wire btfin_vld;
  wire saveEnb;
  wire dinVld;
  reg  x_vld;
  reg  x_vld_dly;
  wire signed [23:0] wrData_im;  // sfix24_En13
  wire [1:0] wrAddr;  // ufix2
  wire wrEnb;
  wire signed [23:0] x_im;  // sfix24_En13
  reg signed [23:0] x_im_dly;  // sfix24_En13
  wire signed [23:0] wrData_re;  // sfix24_En13
  wire signed [23:0] x_re;  // sfix24_En13
  reg signed [23:0] x_re_dly;  // sfix24_En13
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [24:0] Radix22ButterflyG2_btf1_re_reg;  // sfix25
  reg signed [24:0] Radix22ButterflyG2_btf1_im_reg;  // sfix25
  reg signed [24:0] Radix22ButterflyG2_btf2_re_reg;  // sfix25
  reg signed [24:0] Radix22ButterflyG2_btf2_im_reg;  // sfix25
  reg signed [23:0] Radix22ButterflyG2_din_re_dly;  // sfix24
  reg signed [23:0] Radix22ButterflyG2_din_im_dly;  // sfix24
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [23:0] Radix22ButterflyG2_x_re_dly;  // sfix24
  reg signed [23:0] Radix22ButterflyG2_x_im_dly;  // sfix24
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [23:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix24
  reg signed [23:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix24
  reg signed [23:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix24
  reg signed [23:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix24
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [24:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix25_En13
  reg signed [23:0] Radix22ButterflyG2_din_re_dly_next;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG2_din_im_dly_next;  // sfix24_En13
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [23:0] Radix22ButterflyG2_x_re_dly_next;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG2_x_im_dly_next;  // sfix24_En13
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [23:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  // sfix24_En13
  reg  Radix22ButterflyG2_multiply_J_dly1_next;
  reg signed [23:0] xf_re;  // sfix24_En13
  reg signed [23:0] xf_im;  // sfix24_En13
  reg  xf_vld;
  reg signed [23:0] dinf_re;  // sfix24_En13
  reg signed [23:0] dinf_im;  // sfix24_En13
  reg  dinf_vld;
  reg signed [23:0] btf1_re;  // sfix24_En13
  reg signed [23:0] btf1_im;  // sfix24_En13
  reg signed [23:0] btf2_re;  // sfix24_En13
  reg signed [23:0] btf2_im;  // sfix24_En13
  reg  btfout_vld;
  reg signed [24:0] Radix22ButterflyG2_add_cast;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_add_cast_0;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_add_cast_1;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_add_cast_2;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_sub_cast;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_sub_cast_0;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_sub_cast_1;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_sub_cast_2;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_add_cast_3;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_add_cast_4;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_add_cast_5;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_add_cast_6;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_sub_cast_3;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_sub_cast_4;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_sub_cast_5;  // sfix25_En13
  reg signed [24:0] Radix22ButterflyG2_sub_cast_6;  // sfix25_En13


  assign din_re = {dout_7_1_re[22], dout_7_1_re};



  assign din_im = {dout_7_1_im[22], dout_7_1_im};



  assign btfin_vld = dout_7_1_vld & proc_8_enb;



  assign saveEnb =  ~ btfin_vld;



  assign dinVld = dout_7_1_vld & saveEnb;



  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_8_Enb;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld_dly <= x_vld;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(2),
                              .DataWidth(24)
                              )
                            u_dataMEM_im_0_8 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_im),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_8_Addr),
                                              .rd_dout(x_im)
                                              );

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        x_im_dly <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          x_im_dly <= x_im;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(2),
                              .DataWidth(24)
                              )
                            u_dataMEM_re_0_8 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_re),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_8_Addr),
                                              .rd_dout(x_re)
                                              );

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_re_dly <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          x_re_dly <= x_re;
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 25'sb0000000000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 25'sb0000000000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 25'sb0000000000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 25'sb0000000000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_din_im_dly <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_x_im_dly <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_vld,
       dinVld, din_im, din_re, multiply_8_J, x_im_dly, x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_add_cast = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_add_cast_0 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_add_cast_1 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_add_cast_2 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_sub_cast = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_add_cast_3 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_add_cast_4 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_add_cast_5 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_add_cast_6 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 25'sb0000000000000000000000000;
    Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_btf1_re_reg;
    Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_btf1_im_reg;
    Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_btf2_re_reg;
    Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_btf2_im_reg;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[23], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[23], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[23], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[23], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[23], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[23], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[23], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[23], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[23], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[23], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[23], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[23], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[23], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[23], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[23], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[23], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = din_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = din_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_8_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[23:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[23:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[23:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[23:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  SDFCommutator8 u_SDFCOMMUTATOR_8 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .dout_7_1_vld(dout_7_1_vld),
                                    .xf_re(xf_re),  // sfix24_En13
                                    .xf_im(xf_im),  // sfix24_En13
                                    .xf_vld(xf_vld),
                                    .dinf_re(dinf_re),  // sfix24_En13
                                    .dinf_im(dinf_im),  // sfix24_En13
                                    .dinf_vld(dinf_vld),
                                    .btf1_re(btf1_re),  // sfix24_En13
                                    .btf1_im(btf1_im),  // sfix24_En13
                                    .btf2_re(btf2_re),  // sfix24_En13
                                    .btf2_im(btf2_im),  // sfix24_En13
                                    .btfout_vld(btfout_vld),
                                    .wrData_re(wrData_re),  // sfix24_En13
                                    .wrData_im(wrData_im),  // sfix24_En13
                                    .wrAddr(wrAddr),  // ufix2
                                    .wrEnb(wrEnb),
                                    .dout_8_1_re(dout_8_1_re),  // sfix24_En13
                                    .dout_8_1_im(dout_8_1_im),  // sfix24_En13
                                    .dout_8_1_vld(dout_8_1_vld)
                                    );

  assign dinXTwdl_8_1_vld = btfin_vld;

endmodule  // RADIX22FFT_SDF2_8

