// -------------------------------------------------------------
// 
// File Name: hdlsrc\tb_FFT\RADIX22FFT_SDF1_7.v
// Created: 2023-02-08 00:35:50
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_7
// Source Path: tb_FFT/DUT/FFT/RADIX22FFT_SDF1_7
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_7
          (clk,
           reset,
           enb,
           din_7_1_re_dly,
           din_7_1_im_dly,
           din_7_vld_dly,
           rd_7_Addr,
           rd_7_Enb,
           twdl_7_1_re,
           twdl_7_1_im,
           proc_7_enb,
           dout_7_1_re,
           dout_7_1_im,
           dout_7_1_vld,
           dinXTwdl_7_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [21:0] din_7_1_re_dly;  // sfix22_En13
  input   signed [21:0] din_7_1_im_dly;  // sfix22_En13
  input   din_7_vld_dly;
  input   [2:0] rd_7_Addr;  // ufix3
  input   rd_7_Enb;
  input   signed [15:0] twdl_7_1_re;  // sfix16_En14
  input   signed [15:0] twdl_7_1_im;  // sfix16_En14
  input   proc_7_enb;
  output  signed [22:0] dout_7_1_re;  // sfix23_En13
  output  signed [22:0] dout_7_1_im;  // sfix23_En13
  output  dout_7_1_vld;
  output  dinXTwdl_7_1_vld;


  wire signed [22:0] din_re;  // sfix23_En13
  wire signed [22:0] din_im;  // sfix23_En13
  wire signed [22:0] dinXTwdl_re;  // sfix23_En13
  wire signed [22:0] dinXTwdl_im;  // sfix23_En13
  reg  x_vld;
  wire signed [22:0] wrData_im;  // sfix23_En13
  wire [2:0] wrAddr;  // ufix3
  wire wrEnb;
  wire signed [22:0] x_im;  // sfix23_En13
  wire signed [22:0] wrData_re;  // sfix23_En13
  wire signed [22:0] x_re;  // sfix23_En13
  reg signed [23:0] Radix22ButterflyG1_btf1_re_reg;  // sfix24
  reg signed [23:0] Radix22ButterflyG1_btf1_im_reg;  // sfix24
  reg signed [23:0] Radix22ButterflyG1_btf2_re_reg;  // sfix24
  reg signed [23:0] Radix22ButterflyG1_btf2_im_reg;  // sfix24
  reg signed [22:0] Radix22ButterflyG1_x_re_dly1;  // sfix23
  reg signed [22:0] Radix22ButterflyG1_x_im_dly1;  // sfix23
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [22:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix23
  reg signed [22:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix23
  reg signed [22:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix23
  reg signed [22:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix23
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [23:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_add_cast;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_add_cast_1;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_sub_cast;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_sub_cast_1;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_add_cast_2;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_add_cast_3;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_sub_cast_2;  // sfix24_En13
  wire signed [23:0] Radix22ButterflyG1_sub_cast_3;  // sfix24_En13
  reg signed [22:0] xf_re;  // sfix23_En13
  reg signed [22:0] xf_im;  // sfix23_En13
  reg  xf_vld;
  wire signed [22:0] dinXTwdlf_re;  // sfix23_En13
  wire signed [22:0] dinXTwdlf_im;  // sfix23_En13
  wire dinxTwdlf_vld;
  wire signed [22:0] btf1_re;  // sfix23_En13
  wire signed [22:0] btf1_im;  // sfix23_En13
  wire signed [22:0] btf2_re;  // sfix23_En13
  wire signed [22:0] btf2_im;  // sfix23_En13
  reg  btf_vld;


  assign din_re = {din_7_1_re_dly[21], din_7_1_re_dly};



  assign din_im = {din_7_1_im_dly[21], din_7_1_im_dly};



  Complex4Multiply_block1 u_MUL4 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .din_re(din_re),  // sfix23_En13
                                  .din_im(din_im),  // sfix23_En13
                                  .din_7_vld_dly(din_7_vld_dly),
                                  .twdl_7_1_re(twdl_7_1_re),  // sfix16_En14
                                  .twdl_7_1_im(twdl_7_1_im),  // sfix16_En14
                                  .dinXTwdl_re(dinXTwdl_re),  // sfix23_En13
                                  .dinXTwdl_im(dinXTwdl_im),  // sfix23_En13
                                  .dinXTwdl_7_1_vld(dinXTwdl_7_1_vld)
                                  );

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_7_Enb;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(3),
                              .DataWidth(23)
                              )
                            u_dataMEM_im_0_7 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_im),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_7_Addr),
                                              .rd_dout(x_im)
                                              );

  SimpleDualPortRAM_generic #(.AddrWidth(3),
                              .DataWidth(23)
                              )
                            u_dataMEM_re_0_7 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_re),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_7_Addr),
                                              .rd_dout(x_re)
                                              );

  // Radix22ButterflyG1
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 23'sb00000000000000000000000;
        xf_im <= 23'sb00000000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_7_enb && dinXTwdl_7_1_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_7_enb) && dinXTwdl_7_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[22], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[22], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[22], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[22], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[22], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[22], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[22], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[22], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[22:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[22:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[22:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[22:0];



  SDFCommutator7 u_SDFCOMMUTATOR_7 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_7_vld_dly(din_7_vld_dly),
                                    .xf_re(xf_re),  // sfix23_En13
                                    .xf_im(xf_im),  // sfix23_En13
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix23_En13
                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix23_En13
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  // sfix23_En13
                                    .btf1_im(btf1_im),  // sfix23_En13
                                    .btf2_re(btf2_re),  // sfix23_En13
                                    .btf2_im(btf2_im),  // sfix23_En13
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  // sfix23_En13
                                    .wrData_im(wrData_im),  // sfix23_En13
                                    .wrAddr(wrAddr),  // ufix3
                                    .wrEnb(wrEnb),
                                    .dout_7_1_re(dout_7_1_re),  // sfix23_En13
                                    .dout_7_1_im(dout_7_1_im),  // sfix23_En13
                                    .dout_7_1_vld(dout_7_1_vld)
                                    );

endmodule  // RADIX22FFT_SDF1_7

