// -------------------------------------------------------------
// 
// File Name: hdlsrc\tb_FFT\RADIX22FFT_SDF2_10.v
// Created: 2023-02-08 00:35:50
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF2_10
// Source Path: tb_FFT/DUT/FFT/RADIX22FFT_SDF2_10
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF2_10
          (clk,
           reset,
           enb,
           dout_9_1_re,
           dout_9_1_im,
           dout_9_1_vld,
           rd_10_Addr,
           rd_10_Enb,
           proc_10_enb,
           multiply_10_J,
           dout_10_1_re,
           dout_10_1_im,
           dout_10_1_vld,
           dinXTwdl_10_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [24:0] dout_9_1_re;  // sfix25_En13
  input   signed [24:0] dout_9_1_im;  // sfix25_En13
  input   dout_9_1_vld;
  input   rd_10_Addr;
  input   rd_10_Enb;
  input   proc_10_enb;
  input   multiply_10_J;
  output  signed [25:0] dout_10_1_re;  // sfix26_En13
  output  signed [25:0] dout_10_1_im;  // sfix26_En13
  output  dout_10_1_vld;
  output  dinXTwdl_10_1_vld;


  wire signed [25:0] din_re;  // sfix26_En13
  wire signed [25:0] din_im;  // sfix26_En13
  wire saveEnb;
  wire dinVld;
  reg signed [25:0] din_re_dly1;  // sfix26_En13
  reg signed [25:0] btfin_re;  // sfix26_En13
  reg signed [25:0] din_im_dly1;  // sfix26_En13
  reg signed [25:0] btfin_im;  // sfix26_En13
  wire mulIn_vld;
  reg  procEnb_dly1;
  reg  btfin_vld;
  reg  x_vld;
  reg  x_vld_dly;
  reg signed [25:0] x_im;  // sfix26_En13
  reg signed [25:0] x_im_dly;  // sfix26_En13
  wire signed [25:0] wrData_re;  // sfix26_En13
  wire signed [25:0] wrData_im;  // sfix26_En13
  wire wrAddr;  // ufix1
  wire wrEnb;
  reg signed [25:0] twoLocationReg_0_MEM_re_0;  // sfix26
  reg signed [25:0] twoLocationReg_0_MEM_im_0;  // sfix26
  reg signed [25:0] twoLocationReg_0_MEM_re_1;  // sfix26
  reg signed [25:0] twoLocationReg_0_MEM_im_1;  // sfix26
  reg signed [25:0] twoLocationReg_0_dout_re_reg;  // sfix26
  reg signed [25:0] twoLocationReg_0_dout_im_reg;  // sfix26
  reg signed [25:0] twoLocationReg_0_MEM_re_0_next;  // sfix26_En13
  reg signed [25:0] twoLocationReg_0_MEM_im_0_next;  // sfix26_En13
  reg signed [25:0] twoLocationReg_0_MEM_re_1_next;  // sfix26_En13
  reg signed [25:0] twoLocationReg_0_MEM_im_1_next;  // sfix26_En13
  reg signed [25:0] twoLocationReg_0_dout_re_reg_next;  // sfix26_En13
  reg signed [25:0] twoLocationReg_0_dout_im_reg_next;  // sfix26_En13
  reg signed [25:0] x_re;  // sfix26_En13
  reg signed [25:0] x_re_dly;  // sfix26_En13
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [26:0] Radix22ButterflyG2_btf1_re_reg;  // sfix27
  reg signed [26:0] Radix22ButterflyG2_btf1_im_reg;  // sfix27
  reg signed [26:0] Radix22ButterflyG2_btf2_re_reg;  // sfix27
  reg signed [26:0] Radix22ButterflyG2_btf2_im_reg;  // sfix27
  reg signed [25:0] Radix22ButterflyG2_din_re_dly;  // sfix26
  reg signed [25:0] Radix22ButterflyG2_din_im_dly;  // sfix26
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [25:0] Radix22ButterflyG2_x_re_dly;  // sfix26
  reg signed [25:0] Radix22ButterflyG2_x_im_dly;  // sfix26
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [25:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix26
  reg signed [25:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix26
  reg signed [25:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix26
  reg signed [25:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix26
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [26:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix27_En13
  reg signed [25:0] Radix22ButterflyG2_din_re_dly_next;  // sfix26_En13
  reg signed [25:0] Radix22ButterflyG2_din_im_dly_next;  // sfix26_En13
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [25:0] Radix22ButterflyG2_x_re_dly_next;  // sfix26_En13
  reg signed [25:0] Radix22ButterflyG2_x_im_dly_next;  // sfix26_En13
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [25:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  // sfix26_En13
  reg signed [25:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  // sfix26_En13
  reg signed [25:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  // sfix26_En13
  reg signed [25:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  // sfix26_En13
  reg  Radix22ButterflyG2_multiply_J_dly1_next;
  reg signed [25:0] xf_re;  // sfix26_En13
  reg signed [25:0] xf_im;  // sfix26_En13
  reg  xf_vld;
  reg signed [25:0] dinf_re;  // sfix26_En13
  reg signed [25:0] dinf_im;  // sfix26_En13
  reg  dinf_vld;
  reg signed [25:0] btf1_re;  // sfix26_En13
  reg signed [25:0] btf1_im;  // sfix26_En13
  reg signed [25:0] btf2_re;  // sfix26_En13
  reg signed [25:0] btf2_im;  // sfix26_En13
  reg  btfout_vld;
  reg signed [26:0] Radix22ButterflyG2_add_cast;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_add_cast_0;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_add_cast_1;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_add_cast_2;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_sub_cast;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_sub_cast_0;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_sub_cast_1;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_sub_cast_2;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_add_cast_3;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_add_cast_4;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_add_cast_5;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_add_cast_6;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_sub_cast_3;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_sub_cast_4;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_sub_cast_5;  // sfix27_En13
  reg signed [26:0] Radix22ButterflyG2_sub_cast_6;  // sfix27_En13


  assign din_re = {dout_9_1_re[24], dout_9_1_re};



  assign din_im = {dout_9_1_im[24], dout_9_1_im};



  assign saveEnb =  ~ proc_10_enb;



  assign dinVld = dout_9_1_vld & saveEnb;



  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_dly1 <= 26'sb00000000000000000000000000;
      end
      else begin
        if (enb) begin
          din_re_dly1 <= din_re;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        btfin_re <= 26'sb00000000000000000000000000;
      end
      else begin
        if (enb) begin
          btfin_re <= din_re_dly1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        din_im_dly1 <= 26'sb00000000000000000000000000;
      end
      else begin
        if (enb) begin
          din_im_dly1 <= din_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        btfin_im <= 26'sb00000000000000000000000000;
      end
      else begin
        if (enb) begin
          btfin_im <= din_im_dly1;
        end
      end
    end



  assign mulIn_vld = dout_9_1_vld & proc_10_enb;



  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        procEnb_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          procEnb_dly1 <= mulIn_vld;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        btfin_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          btfin_vld <= procEnb_dly1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_10_Enb;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld_dly <= x_vld;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        x_im_dly <= 26'sb00000000000000000000000000;
      end
      else begin
        if (enb) begin
          x_im_dly <= x_im;
        end
      end
    end



  // twoLocationReg_0
  always @(posedge clk or posedge reset)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 26'sb00000000000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 26'sb00000000000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 26'sb00000000000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 26'sb00000000000000000000000000;
        twoLocationReg_0_dout_re_reg <= 26'sb00000000000000000000000000;
        twoLocationReg_0_dout_im_reg <= 26'sb00000000000000000000000000;
      end
      else begin
        if (enb) begin
          twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
          twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
          twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
          twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
          twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
          twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
        end
      end
    end

  always @(rd_10_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_dout_re_reg;
    twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_dout_im_reg;
    if (rd_10_Addr) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end



  always @(posedge clk or posedge reset)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        x_re_dly <= 26'sb00000000000000000000000000;
      end
      else begin
        if (enb) begin
          x_re_dly <= x_re;
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 27'sb000000000000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 27'sb000000000000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 27'sb000000000000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 27'sb000000000000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 26'sb00000000000000000000000000;
        Radix22ButterflyG2_din_im_dly <= 26'sb00000000000000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 26'sb00000000000000000000000000;
        Radix22ButterflyG2_x_im_dly <= 26'sb00000000000000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 26'sb00000000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 26'sb00000000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 26'sb00000000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 26'sb00000000000000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_im,
       btfin_re, btfin_vld, dinVld, din_im, din_re, multiply_10_J, x_im_dly,
       x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_add_cast = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_add_cast_0 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_add_cast_1 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_add_cast_2 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_sub_cast = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_add_cast_3 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_add_cast_4 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_add_cast_5 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_add_cast_6 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 27'sb000000000000000000000000000;
    Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_btf1_re_reg;
    Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_btf1_im_reg;
    Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_btf2_re_reg;
    Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_btf2_im_reg;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[25], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[25], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[25], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[25], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[25], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[25], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[25], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[25], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[25], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[25], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[25], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[25], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[25], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[25], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[25], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[25], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = btfin_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = btfin_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_10_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[25:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[25:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[25:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[25:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  SDFCommutator10 u_SDFCOMMUTATOR_10 (.clk(clk),
                                      .reset(reset),
                                      .enb(enb),
                                      .dout_9_1_vld(dout_9_1_vld),
                                      .xf_re(xf_re),  // sfix26_En13
                                      .xf_im(xf_im),  // sfix26_En13
                                      .xf_vld(xf_vld),
                                      .dinf_re(dinf_re),  // sfix26_En13
                                      .dinf_im(dinf_im),  // sfix26_En13
                                      .dinf_vld(dinf_vld),
                                      .btf1_re(btf1_re),  // sfix26_En13
                                      .btf1_im(btf1_im),  // sfix26_En13
                                      .btf2_re(btf2_re),  // sfix26_En13
                                      .btf2_im(btf2_im),  // sfix26_En13
                                      .btfout_vld(btfout_vld),
                                      .wrData_re(wrData_re),  // sfix26_En13
                                      .wrData_im(wrData_im),  // sfix26_En13
                                      .wrAddr(wrAddr),  // ufix1
                                      .wrEnb(wrEnb),
                                      .dout_10_1_re(dout_10_1_re),  // sfix26_En13
                                      .dout_10_1_im(dout_10_1_im),  // sfix26_En13
                                      .dout_10_1_vld(dout_10_1_vld)
                                      );

  assign dinXTwdl_10_1_vld = btfin_vld;

endmodule  // RADIX22FFT_SDF2_10

