// -------------------------------------------------------------
// 
// File Name: hdlsrc\tb_FFT\RADIX22FFT_SDF1_3.v
// Created: 2023-02-08 00:35:50
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_3
// Source Path: tb_FFT/DUT/FFT/RADIX22FFT_SDF1_3
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_3
          (clk,
           reset,
           enb,
           din_3_1_re_dly,
           din_3_1_im_dly,
           din_3_vld_dly,
           rd_3_Addr,
           rd_3_Enb,
           twdl_3_1_re,
           twdl_3_1_im,
           proc_3_enb,
           dout_3_1_re,
           dout_3_1_im,
           dout_3_1_vld,
           dinXTwdl_3_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [17:0] din_3_1_re_dly;  // sfix18_En13
  input   signed [17:0] din_3_1_im_dly;  // sfix18_En13
  input   din_3_vld_dly;
  input   [6:0] rd_3_Addr;  // ufix7
  input   rd_3_Enb;
  input   signed [15:0] twdl_3_1_re;  // sfix16_En14
  input   signed [15:0] twdl_3_1_im;  // sfix16_En14
  input   proc_3_enb;
  output  signed [18:0] dout_3_1_re;  // sfix19_En13
  output  signed [18:0] dout_3_1_im;  // sfix19_En13
  output  dout_3_1_vld;
  output  dinXTwdl_3_1_vld;


  wire signed [18:0] din_re;  // sfix19_En13
  wire signed [18:0] din_im;  // sfix19_En13
  wire signed [18:0] dinXTwdl_re;  // sfix19_En13
  wire signed [18:0] dinXTwdl_im;  // sfix19_En13
  reg  x_vld;
  wire signed [18:0] wrData_im;  // sfix19_En13
  wire [6:0] wrAddr;  // ufix7
  wire wrEnb;
  wire signed [18:0] x_im;  // sfix19_En13
  wire signed [18:0] wrData_re;  // sfix19_En13
  wire signed [18:0] x_re;  // sfix19_En13
  reg signed [19:0] Radix22ButterflyG1_btf1_re_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf1_im_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf2_re_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf2_im_reg;  // sfix20
  reg signed [18:0] Radix22ButterflyG1_x_re_dly1;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_x_im_dly1;  // sfix19
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix19
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [19:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_add_cast;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_add_cast_1;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_sub_cast;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_sub_cast_1;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_add_cast_2;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_add_cast_3;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_sub_cast_2;  // sfix20_En13
  wire signed [19:0] Radix22ButterflyG1_sub_cast_3;  // sfix20_En13
  reg signed [18:0] xf_re;  // sfix19_En13
  reg signed [18:0] xf_im;  // sfix19_En13
  reg  xf_vld;
  wire signed [18:0] dinXTwdlf_re;  // sfix19_En13
  wire signed [18:0] dinXTwdlf_im;  // sfix19_En13
  wire dinxTwdlf_vld;
  wire signed [18:0] btf1_re;  // sfix19_En13
  wire signed [18:0] btf1_im;  // sfix19_En13
  wire signed [18:0] btf2_re;  // sfix19_En13
  wire signed [18:0] btf2_im;  // sfix19_En13
  reg  btf_vld;


  assign din_re = {din_3_1_re_dly[17], din_3_1_re_dly};



  assign din_im = {din_3_1_im_dly[17], din_3_1_im_dly};



  Complex4Multiply u_MUL4 (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .din_re(din_re),  // sfix19_En13
                           .din_im(din_im),  // sfix19_En13
                           .din_3_vld_dly(din_3_vld_dly),
                           .twdl_3_1_re(twdl_3_1_re),  // sfix16_En14
                           .twdl_3_1_im(twdl_3_1_im),  // sfix16_En14
                           .dinXTwdl_re(dinXTwdl_re),  // sfix19_En13
                           .dinXTwdl_im(dinXTwdl_im),  // sfix19_En13
                           .dinXTwdl_3_1_vld(dinXTwdl_3_1_vld)
                           );

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_3_Enb;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(7),
                              .DataWidth(19)
                              )
                            u_dataMEM_im_0_3 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_im),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_3_Addr),
                                              .rd_dout(x_im)
                                              );

  SimpleDualPortRAM_generic #(.AddrWidth(7),
                              .DataWidth(19)
                              )
                            u_dataMEM_re_0_3 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_re),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_3_Addr),
                                              .rd_dout(x_re)
                                              );

  // Radix22ButterflyG1
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 19'sb0000000000000000000;
        xf_im <= 19'sb0000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_3_enb && dinXTwdl_3_1_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_3_enb) && dinXTwdl_3_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[18], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[18], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[18], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[18], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[18], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[18], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[18], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[18], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[18:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[18:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[18:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[18:0];



  SDFCommutator3 u_SDFCOMMUTATOR_3 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_3_vld_dly(din_3_vld_dly),
                                    .xf_re(xf_re),  // sfix19_En13
                                    .xf_im(xf_im),  // sfix19_En13
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix19_En13
                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix19_En13
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  // sfix19_En13
                                    .btf1_im(btf1_im),  // sfix19_En13
                                    .btf2_re(btf2_re),  // sfix19_En13
                                    .btf2_im(btf2_im),  // sfix19_En13
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  // sfix19_En13
                                    .wrData_im(wrData_im),  // sfix19_En13
                                    .wrAddr(wrAddr),  // ufix7
                                    .wrEnb(wrEnb),
                                    .dout_3_1_re(dout_3_1_re),  // sfix19_En13
                                    .dout_3_1_im(dout_3_1_im),  // sfix19_En13
                                    .dout_3_1_vld(dout_3_1_vld)
                                    );

endmodule  // RADIX22FFT_SDF1_3

