// -------------------------------------------------------------
// 
// File Name: hdlsrc\tb_FFT\RADIX22FFT_CTRL1_8.v
// Created: 2023-02-08 00:35:50
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_CTRL1_8
// Source Path: tb_FFT/DUT/FFT/RADIX22FFT_CTRL1_8
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_CTRL1_8
          (clk,
           reset,
           enb,
           dout_7_1_vld,
           dinXTwdl_8_1_vld,
           rd_8_Addr,
           rd_8_Enb,
           proc_8_enb,
           multiply_8_J);


  input   clk;
  input   reset;
  input   enb;
  input   dout_7_1_vld;
  input   dinXTwdl_8_1_vld;
  output  [1:0] rd_8_Addr;  // ufix2
  output  rd_8_Enb;
  output  proc_8_enb;
  output  multiply_8_J;


  reg [1:0] SDFController_wrCount;  // ufix2
  reg [1:0] SDFController_wrState;  // ufix2
  reg [1:0] SDFController_rdState;  // ufix2
  reg [1:0] SDFController_rdAddr_reg;  // ufix2
  reg  SDFController_procEnb_reg;
  reg [1:0] SDFController_multjState;  // ufix2
  reg  SDFController_multiply_J_reg;
  reg [1:0] SDFController_wrCount_next;  // ufix2
  reg [1:0] SDFController_wrState_next;  // ufix2
  reg [1:0] SDFController_rdState_next;  // ufix2
  reg [1:0] SDFController_rdAddr_reg_next;  // ufix2
  reg  SDFController_procEnb_reg_next;
  reg [1:0] SDFController_multjState_next;  // ufix2
  reg  SDFController_multiply_J_reg_next;
  reg [1:0] rd_8_Addr_1;  // ufix2
  reg  rd_8_Enb_1;
  reg  proc_8_enb_1;
  reg  multiply_8_J_1;


  // SDFController
  always @(posedge clk or posedge reset)
    begin : SDFController_process
      if (reset == 1'b1) begin
        SDFController_wrCount <= 2'b00;
        SDFController_rdAddr_reg <= 2'b00;
        SDFController_wrState <= 2'b00;
        SDFController_rdState <= 2'b00;
        SDFController_multjState <= 2'b00;
        SDFController_procEnb_reg <= 1'b0;
        SDFController_multiply_J_reg <= 1'b0;
      end
      else begin
        if (enb) begin
          SDFController_wrCount <= SDFController_wrCount_next;
          SDFController_wrState <= SDFController_wrState_next;
          SDFController_rdState <= SDFController_rdState_next;
          SDFController_rdAddr_reg <= SDFController_rdAddr_reg_next;
          SDFController_procEnb_reg <= SDFController_procEnb_reg_next;
          SDFController_multjState <= SDFController_multjState_next;
          SDFController_multiply_J_reg <= SDFController_multiply_J_reg_next;
        end
      end
    end

  always @(SDFController_multiply_J_reg, SDFController_multjState,
       SDFController_procEnb_reg, SDFController_rdAddr_reg,
       SDFController_rdState, SDFController_wrCount, SDFController_wrState,
       dinXTwdl_8_1_vld, dout_7_1_vld) begin
    SDFController_wrCount_next = SDFController_wrCount;
    SDFController_wrState_next = SDFController_wrState;
    SDFController_rdState_next = SDFController_rdState;
    SDFController_rdAddr_reg_next = SDFController_rdAddr_reg;
    SDFController_procEnb_reg_next = SDFController_procEnb_reg;
    SDFController_multjState_next = SDFController_multjState;
    SDFController_multiply_J_reg_next = SDFController_multiply_J_reg;
    case ( SDFController_multjState)
      2'b00 :
        begin
          SDFController_multjState_next = 2'b00;
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b10) begin
            SDFController_multjState_next = 2'b10;
          end
        end
      2'b10 :
        begin
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b11;
            SDFController_multiply_J_reg_next = 1'b1;
          end
        end
      2'b11 :
        begin
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b11;
            SDFController_multiply_J_reg_next = 1'b1;
          end
          else begin
            SDFController_multiply_J_reg_next = 1'b0;
            SDFController_multjState_next = 2'b00;
          end
        end
      default :
        begin
          SDFController_multjState_next = 2'b00;
          SDFController_multiply_J_reg_next = 1'b0;
        end
    endcase
    case ( SDFController_rdState)
      2'b00 :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 2'b00;
          rd_8_Enb_1 = 1'b0;
          if (dout_7_1_vld && (SDFController_wrCount == 2'b11)) begin
            SDFController_rdState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          SDFController_rdState_next = 2'b01;
          rd_8_Enb_1 = dinXTwdl_8_1_vld;
          if (dinXTwdl_8_1_vld) begin
            if (SDFController_rdAddr_reg == 2'b11) begin
              SDFController_rdState_next = 2'b10;
            end
            SDFController_rdAddr_reg_next = SDFController_rdAddr_reg + 2'b01;
          end
        end
      2'b10 :
        begin
          rd_8_Enb_1 = 1'b0;
          if (SDFController_rdAddr_reg == 2'b11) begin
            if (dout_7_1_vld && (SDFController_wrCount == 2'b11)) begin
              SDFController_rdState_next = 2'b01;
            end
            else begin
              SDFController_rdState_next = 2'b00;
            end
          end
          SDFController_rdAddr_reg_next = SDFController_rdAddr_reg + 2'b01;
        end
      default :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 2'b00;
          rd_8_Enb_1 = 1'b0;
        end
    endcase
    case ( SDFController_wrState)
      2'b00 :
        begin
          SDFController_wrState_next = 2'b00;
          SDFController_wrCount_next = 2'b00;
          SDFController_procEnb_reg_next = 1'b0;
          if (dout_7_1_vld) begin
            SDFController_wrState_next = 2'b01;
            SDFController_wrCount_next = 2'b01;
          end
        end
      2'b01 :
        begin
          SDFController_wrState_next = 2'b01;
          SDFController_procEnb_reg_next = 1'b0;
          if (dout_7_1_vld) begin
            if (SDFController_wrCount == 2'b11) begin
              SDFController_wrState_next = 2'b10;
              SDFController_procEnb_reg_next = 1'b1;
            end
            else begin
              SDFController_wrState_next = 2'b01;
            end
            SDFController_wrCount_next = SDFController_wrCount + 2'b01;
          end
        end
      2'b10 :
        begin
          SDFController_wrState_next = 2'b10;
          if (dout_7_1_vld) begin
            if (SDFController_wrCount == 2'b11) begin
              SDFController_wrState_next = 2'b01;
              SDFController_procEnb_reg_next = 1'b0;
            end
            else begin
              SDFController_wrState_next = 2'b10;
              SDFController_procEnb_reg_next = 1'b1;
            end
            SDFController_wrCount_next = SDFController_wrCount + 2'b01;
          end
        end
      default :
        begin
          SDFController_wrState_next = 2'b00;
          SDFController_wrCount_next = 2'b11;
          SDFController_procEnb_reg_next = 1'b0;
        end
    endcase
    rd_8_Addr_1 = SDFController_rdAddr_reg;
    proc_8_enb_1 = SDFController_procEnb_reg;
    multiply_8_J_1 = SDFController_multiply_J_reg;
  end



  assign rd_8_Addr = rd_8_Addr_1;

  assign rd_8_Enb = rd_8_Enb_1;

  assign proc_8_enb = proc_8_enb_1;

  assign multiply_8_J = multiply_8_J_1;

endmodule  // RADIX22FFT_CTRL1_8

