// -------------------------------------------------------------
// 
// File Name: hdlsrc\tb_FFT\RADIX22FFT_SDF1_9.v
// Created: 2023-02-08 00:35:50
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_9
// Source Path: tb_FFT/DUT/FFT/RADIX22FFT_SDF1_9
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_9
          (clk,
           reset,
           enb,
           din_9_1_re_dly,
           din_9_1_im_dly,
           din_9_vld_dly,
           rd_9_Addr,
           rd_9_Enb,
           twdl_9_1_re,
           twdl_9_1_im,
           proc_9_enb,
           dout_9_1_re,
           dout_9_1_im,
           dout_9_1_vld,
           dinXTwdl_9_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [23:0] din_9_1_re_dly;  // sfix24_En13
  input   signed [23:0] din_9_1_im_dly;  // sfix24_En13
  input   din_9_vld_dly;
  input   rd_9_Addr;  // ufix1
  input   rd_9_Enb;
  input   signed [15:0] twdl_9_1_re;  // sfix16_En14
  input   signed [15:0] twdl_9_1_im;  // sfix16_En14
  input   proc_9_enb;
  output  signed [24:0] dout_9_1_re;  // sfix25_En13
  output  signed [24:0] dout_9_1_im;  // sfix25_En13
  output  dout_9_1_vld;
  output  dinXTwdl_9_1_vld;


  wire signed [24:0] din_re;  // sfix25_En13
  wire signed [24:0] din_im;  // sfix25_En13
  wire signed [24:0] dinXTwdl_re;  // sfix25_En13
  wire signed [24:0] dinXTwdl_im;  // sfix25_En13
  reg  x_vld;
  wire signed [24:0] wrData_re;  // sfix25_En13
  wire signed [24:0] wrData_im;  // sfix25_En13
  wire wrAddr;  // ufix1
  wire wrEnb;
  reg signed [24:0] twoLocationReg_0_MEM_re_0;  // sfix25
  reg signed [24:0] twoLocationReg_0_MEM_im_0;  // sfix25
  reg signed [24:0] twoLocationReg_0_MEM_re_1;  // sfix25
  reg signed [24:0] twoLocationReg_0_MEM_im_1;  // sfix25
  reg signed [24:0] twoLocationReg_0_dout_re_reg;  // sfix25
  reg signed [24:0] twoLocationReg_0_dout_im_reg;  // sfix25
  reg signed [24:0] twoLocationReg_0_MEM_re_0_next;  // sfix25_En13
  reg signed [24:0] twoLocationReg_0_MEM_im_0_next;  // sfix25_En13
  reg signed [24:0] twoLocationReg_0_MEM_re_1_next;  // sfix25_En13
  reg signed [24:0] twoLocationReg_0_MEM_im_1_next;  // sfix25_En13
  reg signed [24:0] twoLocationReg_0_dout_re_reg_next;  // sfix25_En13
  reg signed [24:0] twoLocationReg_0_dout_im_reg_next;  // sfix25_En13
  reg signed [24:0] x_re;  // sfix25_En13
  reg signed [24:0] x_im;  // sfix25_En13
  reg signed [25:0] Radix22ButterflyG1_btf1_re_reg;  // sfix26
  reg signed [25:0] Radix22ButterflyG1_btf1_im_reg;  // sfix26
  reg signed [25:0] Radix22ButterflyG1_btf2_re_reg;  // sfix26
  reg signed [25:0] Radix22ButterflyG1_btf2_im_reg;  // sfix26
  reg signed [24:0] Radix22ButterflyG1_x_re_dly1;  // sfix25
  reg signed [24:0] Radix22ButterflyG1_x_im_dly1;  // sfix25
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [24:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix25
  reg signed [24:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix25
  reg signed [24:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix25
  reg signed [24:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix25
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [25:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_add_cast;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_add_cast_1;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_sub_cast;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_sub_cast_1;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_add_cast_2;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_add_cast_3;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_sub_cast_2;  // sfix26_En13
  wire signed [25:0] Radix22ButterflyG1_sub_cast_3;  // sfix26_En13
  reg signed [24:0] xf_re;  // sfix25_En13
  reg signed [24:0] xf_im;  // sfix25_En13
  reg  xf_vld;
  wire signed [24:0] dinXTwdlf_re;  // sfix25_En13
  wire signed [24:0] dinXTwdlf_im;  // sfix25_En13
  wire dinxTwdlf_vld;
  wire signed [24:0] btf1_re;  // sfix25_En13
  wire signed [24:0] btf1_im;  // sfix25_En13
  wire signed [24:0] btf2_re;  // sfix25_En13
  wire signed [24:0] btf2_im;  // sfix25_En13
  reg  btf_vld;


  assign din_re = {din_9_1_re_dly[23], din_9_1_re_dly};



  assign din_im = {din_9_1_im_dly[23], din_9_1_im_dly};



  Complex4Multiply_block2 u_MUL4 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .din_re(din_re),  // sfix25_En13
                                  .din_im(din_im),  // sfix25_En13
                                  .din_9_vld_dly(din_9_vld_dly),
                                  .twdl_9_1_re(twdl_9_1_re),  // sfix16_En14
                                  .twdl_9_1_im(twdl_9_1_im),  // sfix16_En14
                                  .dinXTwdl_re(dinXTwdl_re),  // sfix25_En13
                                  .dinXTwdl_im(dinXTwdl_im),  // sfix25_En13
                                  .dinXTwdl_9_1_vld(dinXTwdl_9_1_vld)
                                  );

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_9_Enb;
        end
      end
    end



  // twoLocationReg_0
  always @(posedge clk or posedge reset)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 25'sb0000000000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 25'sb0000000000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 25'sb0000000000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 25'sb0000000000000000000000000;
        twoLocationReg_0_dout_re_reg <= 25'sb0000000000000000000000000;
        twoLocationReg_0_dout_im_reg <= 25'sb0000000000000000000000000;
      end
      else begin
        if (enb) begin
          twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
          twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
          twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
          twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
          twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
          twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
        end
      end
    end

  always @(rd_9_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_dout_re_reg;
    twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_dout_im_reg;
    if (rd_9_Addr == 1'b1) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end



  // Radix22ButterflyG1
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 26'sb00000000000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 26'sb00000000000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 26'sb00000000000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 26'sb00000000000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 25'sb0000000000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 25'sb0000000000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 25'sb0000000000000000000000000;
        xf_im <= 25'sb0000000000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 25'sb0000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 25'sb0000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 25'sb0000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 25'sb0000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_9_enb && dinXTwdl_9_1_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_9_enb) && dinXTwdl_9_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[24], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[24], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[24], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[24], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[24], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[24], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[24], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[24], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[24:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[24:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[24:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[24:0];



  SDFCommutator9 u_SDFCOMMUTATOR_9 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_9_vld_dly(din_9_vld_dly),
                                    .xf_re(xf_re),  // sfix25_En13
                                    .xf_im(xf_im),  // sfix25_En13
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix25_En13
                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix25_En13
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  // sfix25_En13
                                    .btf1_im(btf1_im),  // sfix25_En13
                                    .btf2_re(btf2_re),  // sfix25_En13
                                    .btf2_im(btf2_im),  // sfix25_En13
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  // sfix25_En13
                                    .wrData_im(wrData_im),  // sfix25_En13
                                    .wrAddr(wrAddr),  // ufix1
                                    .wrEnb(wrEnb),
                                    .dout_9_1_re(dout_9_1_re),  // sfix25_En13
                                    .dout_9_1_im(dout_9_1_im),  // sfix25_En13
                                    .dout_9_1_vld(dout_9_1_vld)
                                    );

endmodule  // RADIX22FFT_SDF1_9

